jwt:
  signing-key: 'can'
  expires-time: 604800
  buffer-time: 86400
system:
  env: 'public'  # Change to "develop" to skip authentication for development mode
  addr: 8081
  db-type: 'mysql'
  use-multipoint: true
zap:
  level: 'info'
  format: 'console'
  prefix: '[GO-CLASS]'
  director: 'log'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

mysql:
  path: ''
  config: ''
  db-name: ''
  username: ''
  password: ''
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: false
  log-zap: ""
redis:
  db: 0
  addr: '104.128.94.5:6379'
  password: '12306'