autocode:
  transfer-restart: true
  root: ""
  server: /server
  server-api: /api/v1/autocode
  server-initialize: /initialize
  server-model: /model/autocode
  server-request: /model/autocode/request/
  server-router: /router/autocode
  server-service: /service/autocode
  web: /web/src
  web-api: /api
  web-form: /view
  web-table: /view
  web-flow: /view
jwt:
  signing-key: can
  expires-time: 604800
  buffer-time: 86400
mysql:
  path: ''
  config: ''
  db-name: ''
  username: ''
  password: ''
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: false
  log-zap: ""
redis:
  tables: 0
  addr: 104.128.94.5:6379
  password: "12306"
system:
  env: public
  addr: 8081
  tables-type: ""
  use-multipoint: true
zap:
  level: info
  format: console
  prefix: '[GO-CLASS]'
  director: log
  link-name: latest_log
  showLine: false
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
