jwt:
  signing-key: 'can'
  expires-time: 604800
  buffer-time: 86400
system:
  env: 'public'  # Change to "develop" to skip authentication for development mode
  addr: 8081
  db-type: 'mysql'
  use-multipoint: false
zap:
  level: 'info'
  format: 'console'
  prefix: '[GO-CLASS]'
  director: 'log'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

mysql:
  path: '104.128.94.5:3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'go_class'
  username: 'root'
  password: 'Aa123456'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: false
  log-zap: ""